/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import java.awt.Color;

/**
 * @author victoriapenas y josemariahernandez
 * @version 1.0
 * @since 2020-18-05
 */
public class Interfaz_RegistroClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_Clientes
     */
    public Interfaz_RegistroClientes() {
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_clienteNIF = new javax.swing.JLabel();
        jTextField_clienteNIF = new javax.swing.JTextField();
        jLabel_Bienvenida = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_apellido1 = new javax.swing.JLabel();
        jTextField_apellido1 = new javax.swing.JTextField();
        jLabel_apellido2 = new javax.swing.JLabel();
        jTextField_apellido2 = new javax.swing.JTextField();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jButton_Enviar = new javax.swing.JButton();
        jLabel_password = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel_codUser = new javax.swing.JLabel();
        jTextField_codUser = new javax.swing.JTextField();
        jButton_Limpiar = new javax.swing.JButton();
        jLabel_resultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Registro de Clientes");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_clienteNIF.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_clienteNIF.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_clienteNIF.setText("NIF");

        jLabel_Bienvenida.setFont(new java.awt.Font("Heiti TC", 1, 22)); // NOI18N
        jLabel_Bienvenida.setForeground(new java.awt.Color(254, 255, 249));
        jLabel_Bienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/administrative_tools_64px.png"))); // NOI18N
        jLabel_Bienvenida.setText("   REGISTRATE Y ACCEDE A LA APLICACIÓN!");

        jLabel_nombre.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setText("Nombre");

        jLabel_apellido1.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_apellido1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_apellido1.setText("1º Apellido");

        jLabel_apellido2.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_apellido2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_apellido2.setText("2º Apellido");

        jTextField_apellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_apellido2ActionPerformed(evt);
            }
        });

        jLabel_telefono.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefono.setText("Teléfono");

        jTextField_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonoActionPerformed(evt);
            }
        });

        jLabel_email.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email.setText("E-mail");

        jButton_Enviar.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jButton_Enviar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Enviar.setText("Enviar Formulario");
        jButton_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnviarActionPerformed(evt);
            }
        });

        jLabel_password.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password.setText("Contraseña");

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jLabel_codUser.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_codUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_codUser.setText("Usuario");

        jTextField_codUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codUserActionPerformed(evt);
            }
        });

        jButton_Limpiar.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jButton_Limpiar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Limpiar.setText("Limpiar");
        jButton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimpiarActionPerformed(evt);
            }
        });

        jLabel_resultado.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_resultado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Heiti SC", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("La contraseña debe contener, como mínimo 6 carácteres.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel_Bienvenida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_apellido2)
                                    .addComponent(jLabel_nombre)
                                    .addComponent(jLabel_apellido1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_clienteNIF)
                                    .addComponent(jTextField_nombre)
                                    .addComponent(jTextField_apellido1)
                                    .addComponent(jTextField_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_email, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_telefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_codUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel_password))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField_codUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel_clienteNIF)
                                .addGap(584, 584, 584))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jButton_Enviar)
                        .addGap(26, 26, 26)
                        .addComponent(jButton_Limpiar)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_Bienvenida)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_email)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellido1)
                    .addComponent(jTextField_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_telefono))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellido2)
                    .addComponent(jTextField_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_codUser)
                    .addComponent(jTextField_codUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_clienteNIF)
                    .addComponent(jTextField_clienteNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_password)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Limpiar)
                    .addComponent(jButton_Enviar))
                .addGap(18, 18, 18)
                .addComponent(jLabel_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    /**
     * Método para limpiar los jTextField
     * El JLabel no lo limpiamos porque ahi mostramos el resultado final
     */
    public void limpiar() {
        jTextField_clienteNIF.setText("");
        jTextField_nombre.setText("");
        jTextField_apellido1.setText("");
        jTextField_apellido2.setText("");
        jTextField_telefono.setText("");
        jTextField_email.setText("");
        jTextField_codUser.setText("");
        jPasswordField.setText("");
    }

    private void jButton_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnviarActionPerformed

        // Recojo datos del botón de enviar formulario
        String nif, nom, ape1, ape2, tel, mail, pass, codUser;

        // Stringify un char extraído del passwordfield
        String passText = new String(jPasswordField.getPassword());
        pass = passText;

        // Datos recogidos del formulario
        nif = jTextField_clienteNIF.getText();
        nom = jTextField_nombre.getText();
        ape1 = jTextField_apellido1.getText();
        ape2 = jTextField_apellido2.getText();
        tel = jTextField_telefono.getText();
        mail = jTextField_email.getText();
        codUser = jTextField_codUser.getText();

        // Rol fijado manualmente
        int rol = 1;
        try {
            Usuario nuevoCliente = new Usuario(nif, nom, ape1, ape2, tel, mail, rol, pass, codUser);
            nuevoCliente.insertRegistro(jLabel_resultado);
            limpiar();
        } catch (RCException ex) {
            jLabel_resultado.setForeground(Color.RED);
            jLabel_resultado.setText(ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_EnviarActionPerformed

    private void jTextField_apellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_apellido2ActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_apellido2ActionPerformed

    private void jTextField_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonoActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_telefonoActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jTextField_codUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codUserActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_codUserActionPerformed

    private void jButton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarActionPerformed
        limpiar();
        jLabel_resultado.setText(" ");
    }//GEN-LAST:event_jButton_LimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Enviar;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Bienvenida;
    private javax.swing.JLabel jLabel_apellido1;
    private javax.swing.JLabel jLabel_apellido2;
    private javax.swing.JLabel jLabel_clienteNIF;
    private javax.swing.JLabel jLabel_codUser;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_resultado;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_apellido1;
    private javax.swing.JTextField jTextField_apellido2;
    private javax.swing.JTextField jTextField_clienteNIF;
    private javax.swing.JTextField jTextField_codUser;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
