/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import javax.swing.JOptionPane;

/**
 * @author victoriapenas & josemariahernandez
 * @version 1.0
 * @since 2020-19-05
 */
public class Interfaz_Vehiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_Vehiculos
     */
    ComboBox cb = new ComboBox();

    public Interfaz_Vehiculos() {
        initComponents();
        Object[] marca = cb.combox("VEHICULOS", "marca");
        jComboBox_Marca.removeAllItems();
        for (Object marca1 : marca) {
        jComboBox_Marca.addItem(marca1);
        }
        
        Object[] clase = cb.combox("VEHICULOS", "clase");
        jComboBox_Clase.removeAllItems();
        for (Object clase1 : clase) {
        jComboBox_Clase.addItem(clase1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Marca = new javax.swing.JLabel();
        jComboBox_Marca = new javax.swing.JComboBox();
        jLabel_Modelo = new javax.swing.JLabel();
        jTextField_Modelo = new javax.swing.JTextField();
        jLabel_Clase = new javax.swing.JLabel();
        jComboBox_Clase = new javax.swing.JComboBox();
        jLabel_Matricula = new javax.swing.JLabel();
        jLabel_Puertas = new javax.swing.JLabel();
        jSpinner_Puertas = new javax.swing.JSpinner();
        jTextField_Matricula = new javax.swing.JTextField();
        jLabel_Precio = new javax.swing.JLabel();
        jTextField_Precio = new javax.swing.JTextField();
        jCheckBox_Disponible = new javax.swing.JCheckBox();
        jButton_Guardar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        jLabel_Marca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Marca.setText("Marca");

        jComboBox_Marca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox_Marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MarcaActionPerformed(evt);
            }
        });

        jLabel_Modelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Modelo.setText("Modelo");

        jTextField_Modelo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel_Clase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Clase.setText("Clase");

        jComboBox_Clase.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox_Clase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ClaseActionPerformed(evt);
            }
        });

        jLabel_Matricula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Matricula.setText("Matrícula");

        jLabel_Puertas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Puertas.setText("Nº Puertas");

        jSpinner_Puertas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextField_Matricula.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel_Precio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Precio.setText("Precio");

        jTextField_Precio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jCheckBox_Disponible.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox_Disponible.setText("  Disponible");

        jButton_Guardar.setText("Guardar");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_Precio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_Clase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Matricula, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Puertas, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox_Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton_Salir))
                    .addComponent(jTextField_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_Puertas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Matricula)
                    .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Puertas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner_Puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Clase)
                        .addComponent(jLabel_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Salir)
                    .addComponent(jCheckBox_Disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void limpiar() {
        jTextField_Matricula.setText("");
        jComboBox_Marca.removeAllItems();
        jComboBox_Clase.removeAllItems();
        jTextField_Modelo.setText("");
    }
    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SalirActionPerformed

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        String mat, mar, mod, strClase;

        mat = jTextField_Matricula.getText();
        mod = jTextField_Modelo.getText();
        
        // Conversión de los ComboBox a toString
        mar = jComboBox_Marca.getSelectedItem().toString();
        strClase = jComboBox_Clase.getSelectedItem().toString();
        // Char de Clase
        char cClase = strClase.charAt(0);

        // Conversión del getText a double
        double precio = Double.parseDouble(jTextField_Precio.getText());

        Control_Vehiculo au = new Control_Vehiculo();
        if (!mat.equals("") && !mod.equals("") && !mar.equals("") && !strClase.equals("")) {
            if (au.registrarVehiculo(mat, mod, mar, cClase, precio)) {
                JOptionPane.showMessageDialog(null, "El vehículo se registró con éxito.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                limpiar();

            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el vehículo.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos obligatorios.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jComboBox_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MarcaActionPerformed

    private void jComboBox_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ClaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JCheckBox jCheckBox_Disponible;
    private javax.swing.JComboBox jComboBox_Clase;
    private javax.swing.JComboBox jComboBox_Marca;
    private javax.swing.JLabel jLabel_Clase;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_Matricula;
    private javax.swing.JLabel jLabel_Modelo;
    private javax.swing.JLabel jLabel_Precio;
    private javax.swing.JLabel jLabel_Puertas;
    private javax.swing.JSpinner jSpinner_Puertas;
    private javax.swing.JTextField jTextField_Matricula;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_Precio;
    // End of variables declaration//GEN-END:variables
}
