/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import static RentaCar.Consultas_BBDD.listarClientes;
import static RentaCar.Consultas_BBDD.obtenerConexion;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * 
 * @author victoriapenas
 */
public class Interfaz_ListarClientes extends javax.swing.JInternalFrame {
    private ResultSet rs;
    private Connection con;
    private PreparedStatement pst;
    private ResulsetModeloTabla modelo;

    /**
     * Creates new form Interfaz_ListarClientes
     */
    public Interfaz_ListarClientes() {
        initComponents();
        this.setBounds(300, 300, 600, 400);
        this.setVisible(true);
        this.moveToFront();
        try {
            con = obtenerConexion();
            pst = con.prepareStatement(listarClientes(),ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = pst.executeQuery();
            modelo = new ResulsetModeloTabla(rs);
            JTable tabla = new JTable(modelo);
            this.add(new JScrollPane(tabla),BorderLayout.CENTER);
            validate();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setTitle("LISTADO DE CLIENTES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Clase interna para rellenar el JTable de Interfaz_ListarClientes
     */
    
}
