/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import static RentaCar.Consultas_BBDD.obtenerConexion;
import static RentaCar.Consultas_BBDD.selectVehiculos;
import static RentaCar.Impresora.imprimir;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Chema
 */
public class Interfaz_Reservas extends javax.swing.JInternalFrame {

    ArrayList<Moto> listaMotos = new ArrayList<>();
    ArrayList<Coche> listaCoches = new ArrayList<>();
    ArrayList<Caravana> listaCaravanas = new ArrayList<>();

    /**
     * Creates new form Interfaz_contratos
     */
    public Interfaz_Reservas() {
        initComponents();
        try {
            mostrarVehiculosRes(listaCoches,listaMotos,listaCaravanas);
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz_Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }

        /**
         * Permite rellenar los campos sólo con seleccionar las rows
         */
        jTable_Vehiculos.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            int fila = jTable_Vehiculos.getSelectedRow();
            TableModel model = jTable_Vehiculos.getModel();
            jTextField_matricula.setText(model.getValueAt(fila, 0).toString());
            jTextField_marca.setText(model.getValueAt(fila, 1).toString());
            jTextField_modelo.setText(model.getValueAt(fila, 2).toString());
            jTextField_precioDia.setText(model.getValueAt(fila, 3).toString());
            jTextField_clase.setText(model.getValueAt(fila, 4).toString());
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable_Vehiculos = new javax.swing.JTable();
        jPanel_datosCliente = new javax.swing.JPanel();
        jLabel_infoCliente = new javax.swing.JLabel();
        jLabel_NIF = new javax.swing.JLabel();
        jLabel_nombreCliente = new javax.swing.JLabel();
        jTextField_nombrecliente = new javax.swing.JTextField();
        jLabel_apellido1 = new javax.swing.JLabel();
        jTextField_apellido1 = new javax.swing.JTextField();
        jLabel_apellido2 = new javax.swing.JLabel();
        jTextField_apellido2 = new javax.swing.JTextField();
        jTextField_NIF = new javax.swing.JTextField();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jPanel_datosVehiculo = new javax.swing.JPanel();
        jLabel_infoVehiculo = new javax.swing.JLabel();
        jLabel_matricula = new javax.swing.JLabel();
        jTextField_matricula = new javax.swing.JTextField();
        jLabel_marca = new javax.swing.JLabel();
        jTextField_marca = new javax.swing.JTextField();
        jLabel_modelo = new javax.swing.JLabel();
        jTextField_modelo = new javax.swing.JTextField();
        jLabel_precioDia = new javax.swing.JLabel();
        jTextField_precioDia = new javax.swing.JTextField();
        jLabel_clase = new javax.swing.JLabel();
        jTextField_clase = new javax.swing.JTextField();
        jLabel_cilindrada = new javax.swing.JLabel();
        jTextField_cilindrada = new javax.swing.JTextField();
        jLabel_potenciaMotor = new javax.swing.JLabel();
        jTextField_potenciaMotor = new javax.swing.JTextField();
        jLabel_numPuertas = new javax.swing.JLabel();
        jTextField_numPuertas = new javax.swing.JTextField();
        jCheckBox_wc = new javax.swing.JCheckBox();
        jPanel_datosReserva = new javax.swing.JPanel();
        jLabel_infoReserva = new javax.swing.JLabel();
        jLabel_numReserva = new javax.swing.JLabel();
        jTextField_numReserva = new javax.swing.JTextField();
        jLabel_fechaSolicitud = new javax.swing.JLabel();
        jTextField_fechaSolicitud = new javax.swing.JTextField();
        jLabel_fechaRecogida = new javax.swing.JLabel();
        jDateChooser_recogida = new com.toedter.calendar.JDateChooser();
        jLabel_horaRecogida = new javax.swing.JLabel();
        jComboBox_horaRecogida = new javax.swing.JComboBox<>();
        jLabel_fechaDevolucion = new javax.swing.JLabel();
        jDateChooser_devolucion = new com.toedter.calendar.JDateChooser();
        jLabel_horaDevolucion = new javax.swing.JLabel();
        jComboBox_horaDevolucion = new javax.swing.JComboBox<>();
        Observaciones = new java.awt.TextField();
        jLabel_Observaciones = new javax.swing.JLabel();
        jPanel_botonera = new javax.swing.JPanel();
        jButton_guardar = new javax.swing.JButton();
        jButton_limpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registro de vehículos");

        jTable_Vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Marca", "Modelo", "Precio", "Clase", "Nº Puertas", "Motor", "WC", "Cilindrada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Vehiculos.getTableHeader().setResizingAllowed(false);
        jTable_Vehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_VehiculosMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(jTable_Vehiculos);
        if (jTable_Vehiculos.getColumnModel().getColumnCount() > 0) {
            jTable_Vehiculos.getColumnModel().getColumn(0).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(1).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(2).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(3).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(4).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(4).setPreferredWidth(45);
            jTable_Vehiculos.getColumnModel().getColumn(5).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(6).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(7).setResizable(false);
            jTable_Vehiculos.getColumnModel().getColumn(7).setPreferredWidth(35);
            jTable_Vehiculos.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel_infoCliente.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_infoCliente.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_infoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_infoCliente.setText("Datos cliente");

        jLabel_NIF.setText("NIF");

        jLabel_nombreCliente.setText("Nombre");

        jTextField_nombrecliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_apellido1.setText("1º Apellido");

        jTextField_apellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_apellido2.setText("2º Apellido");

        jTextField_apellido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_NIF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_NIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NIFActionPerformed(evt);
            }
        });

        jLabel_telefono.setText("Teléfono");

        jTextField_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_email.setText("E-Mail");

        jTextField_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel_datosClienteLayout = new javax.swing.GroupLayout(jPanel_datosCliente);
        jPanel_datosCliente.setLayout(jPanel_datosClienteLayout);
        jPanel_datosClienteLayout.setHorizontalGroup(
            jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_infoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_datosClienteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_NIF)
                    .addComponent(jLabel_nombreCliente)
                    .addComponent(jLabel_apellido1)
                    .addComponent(jLabel_apellido2)
                    .addComponent(jLabel_telefono)
                    .addComponent(jLabel_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_NIF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nombrecliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_apellido1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_telefono)
                        .addComponent(jTextField_apellido2)
                        .addComponent(jTextField_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        jPanel_datosClienteLayout.setVerticalGroup(
            jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_infoCliente)
                .addGap(18, 18, 18)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_NIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NIF))
                .addGap(12, 12, 12)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombreCliente)
                    .addComponent(jTextField_nombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellido1)
                    .addComponent(jTextField_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_apellido2)
                    .addComponent(jTextField_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_telefono)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_infoVehiculo.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_infoVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_infoVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_infoVehiculo.setText("Datos vehículo");

        jLabel_matricula.setText("Matrícula");

        jTextField_matricula.setEditable(false);
        jTextField_matricula.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_matricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_matriculaActionPerformed(evt);
            }
        });

        jLabel_marca.setText("Marca");

        jTextField_marca.setEditable(false);
        jTextField_marca.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_modelo.setText("Modelo");

        jTextField_modelo.setEditable(false);
        jTextField_modelo.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_precioDia.setText("Precio / Día");

        jTextField_precioDia.setEditable(false);
        jTextField_precioDia.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_precioDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_clase.setText("Clase");

        jTextField_clase.setEditable(false);
        jTextField_clase.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_clase.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_cilindrada.setText("Cilindrada");

        jTextField_cilindrada.setEditable(false);
        jTextField_cilindrada.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_cilindrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_potenciaMotor.setText("Motor");

        jTextField_potenciaMotor.setEditable(false);
        jTextField_potenciaMotor.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_potenciaMotor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_numPuertas.setText("Nº Puertas");

        jTextField_numPuertas.setEditable(false);
        jTextField_numPuertas.setForeground(new java.awt.Color(51, 51, 55));
        jTextField_numPuertas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_numPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numPuertasActionPerformed(evt);
            }
        });

        jCheckBox_wc.setText("Dispone WC");

        javax.swing.GroupLayout jPanel_datosVehiculoLayout = new javax.swing.GroupLayout(jPanel_datosVehiculo);
        jPanel_datosVehiculo.setLayout(jPanel_datosVehiculoLayout);
        jPanel_datosVehiculoLayout.setHorizontalGroup(
            jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_infoVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_datosVehiculoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_marca)
                    .addComponent(jLabel_matricula)
                    .addComponent(jLabel_modelo)
                    .addComponent(jLabel_precioDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_precioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosVehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel_numPuertas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_numPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_clase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_datosVehiculoLayout.createSequentialGroup()
                        .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_potenciaMotor)
                            .addComponent(jLabel_cilindrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_wc)
                            .addComponent(jTextField_potenciaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel_datosVehiculoLayout.setVerticalGroup(
            jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_infoVehiculo)
                .addGap(18, 18, 18)
                .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_matricula)
                    .addComponent(jLabel_clase)
                    .addComponent(jTextField_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_numPuertas)
                    .addComponent(jTextField_numPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosVehiculoLayout.createSequentialGroup()
                        .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_marca)
                            .addComponent(jTextField_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_cilindrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_modelo)
                            .addComponent(jTextField_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_potenciaMotor)))
                    .addGroup(jPanel_datosVehiculoLayout.createSequentialGroup()
                        .addComponent(jTextField_cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_potenciaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_precioDia)
                        .addComponent(jTextField_precioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox_wc))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel_infoReserva.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_infoReserva.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_infoReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_infoReserva.setText("Datos Reserva");

        jLabel_numReserva.setText("Nº Reserva");

        jTextField_numReserva.setEditable(false);
        jTextField_numReserva.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_numReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numReservaActionPerformed(evt);
            }
        });

        jLabel_fechaSolicitud.setText("Fecha Solicitud");

        jTextField_fechaSolicitud.setEditable(false);
        jTextField_fechaSolicitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel_fechaRecogida.setText("Fecha Recogida");

        jDateChooser_recogida.setDateFormatString("dd-MM-yyyy");

        jLabel_horaRecogida.setText("Hora Recogida");

        jComboBox_horaRecogida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));

        jLabel_fechaDevolucion.setText("Fecha Devolución");

        jDateChooser_devolucion.setDateFormatString("dd-MM-yyyy");

        jLabel_horaDevolucion.setText("Hora Devolución");

        jComboBox_horaDevolucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));

        javax.swing.GroupLayout jPanel_datosReservaLayout = new javax.swing.GroupLayout(jPanel_datosReserva);
        jPanel_datosReserva.setLayout(jPanel_datosReservaLayout);
        jPanel_datosReservaLayout.setHorizontalGroup(
            jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_infoReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_datosReservaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_numReserva)
                    .addComponent(jLabel_fechaSolicitud)
                    .addComponent(jLabel_fechaRecogida)
                    .addComponent(jLabel_horaRecogida)
                    .addComponent(jLabel_fechaDevolucion)
                    .addComponent(jLabel_horaDevolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosReservaLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_numReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jTextField_fechaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jComboBox_horaRecogida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_horaDevolucion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser_recogida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jDateChooser_devolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        jPanel_datosReservaLayout.setVerticalGroup(
            jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_infoReserva)
                .addGap(18, 18, 18)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_numReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_numReserva))
                .addGap(12, 12, 12)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fechaSolicitud)
                    .addComponent(jTextField_fechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_fechaRecogida)
                    .addComponent(jDateChooser_recogida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_horaRecogida)
                    .addComponent(jComboBox_horaRecogida, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_fechaDevolucion)
                    .addComponent(jDateChooser_devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_horaDevolucion)
                    .addComponent(jComboBox_horaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Observaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservacionesActionPerformed(evt);
            }
        });

        jLabel_Observaciones.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jLabel_Observaciones.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Observaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Observaciones.setText("Observaciones");

        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        jButton_limpiar.setText("Limpiar");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_botoneraLayout = new javax.swing.GroupLayout(jPanel_botonera);
        jPanel_botonera.setLayout(jPanel_botoneraLayout);
        jPanel_botoneraLayout.setHorizontalGroup(
            jPanel_botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_botoneraLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jButton_limpiar)
                .addGap(29, 29, 29)
                .addComponent(jButton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_botoneraLayout.setVerticalGroup(
            jPanel_botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_botoneraLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel_botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_datosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jPanel_datosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_datosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jPanel_botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_datosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_datosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jPanel_datosVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel_Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Observaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void actualizarFechas() {
        Date fecha = new Date();
        String hoy = fecha.getDate() + "/"
                + (fecha.getMonth() + 1) + "/"
                + (fecha.getYear() + 1900);
        jTextField_fechaSolicitud.setText(hoy);
    }

    /**
     * Método para limpiar los campos
     */
    public void limpiar() {
        jTextField_NIF.setText("");
        jTextField_apellido1.setText("");
        jTextField_apellido2.setText("");
        jTextField_cilindrada.setText("");
        jTextField_clase.setText("");
        jTextField_email.setText("");
        jTextField_marca.setText("");
        jTextField_matricula.setText("");
        jTextField_modelo.setText("");
        jTextField_nombrecliente.setText("");
        jTextField_numReserva.setText("");
        jTextField_potenciaMotor.setText("");
        jTextField_numPuertas.setText("");
        jTextField_precioDia.setText("");
        jTextField_telefono.setText("");
        Observaciones.setText("");
        jCheckBox_wc.setSelected(false);
        jComboBox_horaDevolucion.setSelectedItem(" ");
        jComboBox_horaRecogida.setSelectedItem(" ");
        jDateChooser_devolucion.setCalendar(null);
        jDateChooser_recogida.setCalendar(null);
    }

    /**
     * //*************PENDIENTE*************
     */
    public ArrayList mostrarVehiculosRes(ArrayList<Coche> listaCoches,
            ArrayList<Moto> listaMotos, ArrayList<Caravana> listaCaravanas) throws SQLException {
        ResultSet rs;
        Connection con;
        PreparedStatement pst;
        try {
            con = obtenerConexion();
            pst = con.prepareStatement(selectVehiculos(), ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            rs = pst.executeQuery();
            Moto moto;
            Coche coche;
            Caravana caravana;
            while (rs.next()) {
                try {
                    coche = new Coche(rs.getInt("numeropuertas"), rs.getInt("potenciapotor"),
                            rs.getString("matricula"), rs.getString("marca"), rs.getString("modelo"),
                            rs.getDouble("precioDia"), rs.getString("clase").charAt(0), rs.getBoolean("retirado"));
                    // TODO comprobar que el rs del boolean es true
                    listaCoches.add(coche);
                    return listaCoches;

                } catch (SQLException ex) {
                    Logger.getLogger(Coche.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    caravana = new Caravana(rs.getInt("potenciaMotor"), rs.getBoolean("wc"),
                            rs.getString("matricula"), rs.getString("marca"), rs.getString("modelo"),
                            rs.getDouble("precioDia"), rs.getString("clase").charAt(0));
                    // TODO comprobar que el rs del boolean es true
                    listaCaravanas.add(caravana);
                } catch (SQLException ex) {
                    Logger.getLogger(Coche.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    moto = new Moto(rs.getInt("cilindrada"), rs.getString("matricula"),
                            rs.getString("marca"), rs.getString("modelo"),
                            rs.getDouble("precioDia"), rs.getString("clase").charAt(0));
                    // TODO comprobar que el rs del boolean es true
                    listaMotos.add(moto);
                    return listaMotos;

                } catch (SQLException ex) {
                    Logger.getLogger(Coche.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return listaCaravanas;

    }

    public void mostrarVehiculosJtable(ArrayList<Coche> lista) {
        DefaultTableModel model = (DefaultTableModel) jTable_Vehiculos.getModel();
        Object[] filaCoches = new Object[7];
        for (int i = 0; i < lista.size(); i++) {
            filaCoches[0] = lista.get(i).getMatricula();
            filaCoches[1] = lista.get(i).getMarca();
            filaCoches[2] = lista.get(i).getModelo();
            filaCoches[3] = lista.get(i).getPrecioDia();
            filaCoches[4] = lista.get(i).getClase();
            filaCoches[5] = lista.get(i).getPotenciaMotor();
            filaCoches[6] = lista.get(i).getNumeroPuertas();
            model.addRow(filaCoches);
        }
    }


    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO: Guardar en Reservas BBDD
        imprimir(this);
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jTextField_NIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NIFActionPerformed
    }//GEN-LAST:event_jTextField_NIFActionPerformed

    private void jTextField_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_matriculaActionPerformed
    }//GEN-LAST:event_jTextField_matriculaActionPerformed

    private void jTable_VehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_VehiculosMouseClicked
    }//GEN-LAST:event_jTable_VehiculosMouseClicked

    private void jTextField_numReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numReservaActionPerformed
    }//GEN-LAST:event_jTextField_numReservaActionPerformed

    private void ObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservacionesActionPerformed
    }//GEN-LAST:event_ObservacionesActionPerformed

    private void jTextField_numPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numPuertasActionPerformed
    }//GEN-LAST:event_jTextField_numPuertasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Observaciones;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JCheckBox jCheckBox_wc;
    private javax.swing.JComboBox<String> jComboBox_horaDevolucion;
    private javax.swing.JComboBox<String> jComboBox_horaRecogida;
    private com.toedter.calendar.JDateChooser jDateChooser_devolucion;
    private com.toedter.calendar.JDateChooser jDateChooser_recogida;
    private javax.swing.JLabel jLabel_NIF;
    private javax.swing.JLabel jLabel_Observaciones;
    private javax.swing.JLabel jLabel_apellido1;
    private javax.swing.JLabel jLabel_apellido2;
    private javax.swing.JLabel jLabel_cilindrada;
    private javax.swing.JLabel jLabel_clase;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_fechaDevolucion;
    private javax.swing.JLabel jLabel_fechaRecogida;
    private javax.swing.JLabel jLabel_fechaSolicitud;
    private javax.swing.JLabel jLabel_horaDevolucion;
    private javax.swing.JLabel jLabel_horaRecogida;
    private javax.swing.JLabel jLabel_infoCliente;
    private javax.swing.JLabel jLabel_infoReserva;
    private javax.swing.JLabel jLabel_infoVehiculo;
    private javax.swing.JLabel jLabel_marca;
    private javax.swing.JLabel jLabel_matricula;
    private javax.swing.JLabel jLabel_modelo;
    private javax.swing.JLabel jLabel_nombreCliente;
    private javax.swing.JLabel jLabel_numPuertas;
    private javax.swing.JLabel jLabel_numReserva;
    private javax.swing.JLabel jLabel_potenciaMotor;
    private javax.swing.JLabel jLabel_precioDia;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel_botonera;
    private javax.swing.JPanel jPanel_datosCliente;
    private javax.swing.JPanel jPanel_datosReserva;
    private javax.swing.JPanel jPanel_datosVehiculo;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable_Vehiculos;
    private javax.swing.JTextField jTextField_NIF;
    private javax.swing.JTextField jTextField_apellido1;
    private javax.swing.JTextField jTextField_apellido2;
    private javax.swing.JTextField jTextField_cilindrada;
    private javax.swing.JTextField jTextField_clase;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_fechaSolicitud;
    private javax.swing.JTextField jTextField_marca;
    private javax.swing.JTextField jTextField_matricula;
    private javax.swing.JTextField jTextField_modelo;
    private javax.swing.JTextField jTextField_nombrecliente;
    private javax.swing.JTextField jTextField_numPuertas;
    private javax.swing.JTextField jTextField_numReserva;
    private javax.swing.JTextField jTextField_potenciaMotor;
    private javax.swing.JTextField jTextField_precioDia;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
