/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import static RentaCar.Usuario.comprobarRol;
import static RentaCar.Usuario.comprobarUsuario;
import static RentaCar.Vehiculo.listarVehiculos;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author victoriapenas
 */
public class Interfaz_Main extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Main
     */
    public Interfaz_Main() {
        initComponents();
    }

    /*@Override
        public Dimension getPreferredSize() {
            return new Dimension(imagen.getWidth(), imagen.getHeight());
        }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){
            @Override
            public void paintComponent(Graphics g){
                Image imagen = null;
                super.paintComponent(g);

                try {
                    imagen = ImageIO.read(new File("src/image/fondo-main.png"));
                } catch (IOException ex) {
                    System.out.println("La imagen no se encuentra");
                }

                g.drawImage(imagen, 0, 0, null);
            }
        };
        jLabel_bienvenidos = new javax.swing.JLabel();
        jButton_ConsultarVeh = new javax.swing.JButton();
        jButton_Registrarse = new javax.swing.JButton();
        jButton_Acceder = new javax.swing.JButton();
        jLabel_Mensaje = new javax.swing.JLabel();
        jLabel_Usuario = new javax.swing.JLabel();
        jTextField_Usuario = new javax.swing.JTextField();
        jLabel_Contraseña = new javax.swing.JLabel();
        jPasswordField_Contraseña = new javax.swing.JPasswordField();
        jLabel_verificacionUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME RENTACAR");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setToolTipText("");

        jLabel_bienvenidos.setFont(new java.awt.Font("Heiti TC", 1, 24)); // NOI18N
        jLabel_bienvenidos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bienvenidos.setText("BIENVENID@S");

        jButton_ConsultarVeh.setBackground(new java.awt.Color(255, 255, 255));
        jButton_ConsultarVeh.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jButton_ConsultarVeh.setForeground(new java.awt.Color(0, 0, 0));
        jButton_ConsultarVeh.setText("CONSULTAR VEHICULOS");
        jButton_ConsultarVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultarVehActionPerformed(evt);
            }
        });

        jButton_Registrarse.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Registrarse.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jButton_Registrarse.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Registrarse.setText("REGISTRARSE");
        jButton_Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarseActionPerformed(evt);
            }
        });

        jButton_Acceder.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Acceder.setFont(new java.awt.Font("Heiti TC", 1, 18)); // NOI18N
        jButton_Acceder.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Acceder.setText("ACCEDER");
        jButton_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AccederActionPerformed(evt);
            }
        });

        jLabel_Mensaje.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel_Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mensaje.setText("¡Este es el RentaCar de Vicky y Chema!");

        jLabel_Usuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Usuario.setText("USUARIO");

        jTextField_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsuarioActionPerformed(evt);
            }
        });

        jLabel_Contraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Contraseña.setText("CONTRASEÑA");

        jPasswordField_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_ContraseñaActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel_bienvenidos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_ConsultarVeh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_Registrarse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton_Acceder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Mensaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextField_Usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_Contraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPasswordField_Contraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel_verificacionUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel_bienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel_Mensaje))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_ConsultarVeh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jButton_Registrarse)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Acceder, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_verificacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Usuario)
                            .addComponent(jPasswordField_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel_bienvenidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Acceder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ConsultarVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_verificacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_ContraseñaActionPerformed

    private void jTextField_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsuarioActionPerformed

    private void jButton_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AccederActionPerformed
        int rol;
        try {
            String passText = new String(jPasswordField_Contraseña.getPassword());
            String pass = passText;
            boolean encontrado = comprobarUsuario(jTextField_Usuario.getText(), pass);
            if (encontrado) {
                rol = comprobarRol(jTextField_Usuario.getText());
                if (rol == 1) {
                    //TODO JFrame MENU DEL CLIENTE
                } else if (rol == 2) {
                    //TODO eliminar si nos quedamos con el dispose --> this.setClosed(true);
                    Interfaz_Administrador admin = new Interfaz_Administrador();
                    admin.setVisible(rootPaneCheckingEnabled);
                    this.dispose();
                }
                //TODO tendriamos que encontrar la forma si el usuario se valida, se cierre el JFram Interfaz Main
            } else {
                jLabel_verificacionUsuario.setForeground(Color.RED);
                jLabel_verificacionUsuario.setText("Las claves indicadas no son correctas."
                        + "Intentalo de nuevo");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* TODO --> dejar o quitar el Acceso a jframe interno de Interfaz_Login
        Interfaz_Login ventanaLogin = new Interfaz_Login();
        jDesktopPane1.add(ventanaLogin);
        ventanaLogin.setVisible(rootPaneCheckingEnabled);
         */
    }//GEN-LAST:event_jButton_AccederActionPerformed

    private void jButton_RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarseActionPerformed
        Interfaz_RegistroClientes cli = new Interfaz_RegistroClientes();
        jDesktopPane1.add(cli);
        cli.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButton_RegistrarseActionPerformed

    private void jButton_ConsultarVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultarVehActionPerformed
        Interfaz_ListarVehiculos listarVehi = new Interfaz_ListarVehiculos();
        jDesktopPane1.add(listarVehi);
        listarVehi.setVisible(rootPaneCheckingEnabled);
        try {
            listarVehiculos(listarVehi);
        } catch (SQLException ex) {
            System.out.println("error en la BBDD");
        }
    }//GEN-LAST:event_jButton_ConsultarVehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acceder;
    private javax.swing.JButton jButton_ConsultarVeh;
    private javax.swing.JButton jButton_Registrarse;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_Mensaje;
    private javax.swing.JLabel jLabel_Usuario;
    private javax.swing.JLabel jLabel_bienvenidos;
    private javax.swing.JLabel jLabel_verificacionUsuario;
    private javax.swing.JPasswordField jPasswordField_Contraseña;
    private javax.swing.JTextField jTextField_Usuario;
    // End of variables declaration//GEN-END:variables
}
