/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author victoriapenas & josemariahernandez
 * @version 1.0
 */
public class Interfaz_ListarVehiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_ListarVehiculos
     */
    public Interfaz_ListarVehiculos() {
        initComponents();
    }

    public JLabel getTotalVehiculos() {
        return totalVehiculos;
    }

    public void setTotalVehiculos(JLabel totalVehiculos) {
        this.totalVehiculos = totalVehiculos;
    }

    public JTextArea getVehiculosEncontrados() {
        return vehiculosEncontrados;
    }

    public void setVehiculosEncontrados(JTextArea vehiculosEncontrados) {
        this.vehiculosEncontrados = vehiculosEncontrados;
    }

    public JScrollPane getVentanaVehiculos() {
        return ventanaVehiculos;
    }

    public void setVentanaVehiculos(JScrollPane ventanaVehiculos) {
        this.ventanaVehiculos = ventanaVehiculos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaVehiculos = new javax.swing.JScrollPane();
        vehiculosEncontrados = new javax.swing.JTextArea();
        totalVehiculos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);

        vehiculosEncontrados.setColumns(20);
        vehiculosEncontrados.setRows(5);
        ventanaVehiculos.setViewportView(vehiculosEncontrados);

        totalVehiculos.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        totalVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        totalVehiculos.setText("vechiculos encontrados");
        totalVehiculos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                totalVehiculosComponentMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ventanaVehiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ventanaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalVehiculosComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_totalVehiculosComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_totalVehiculosComponentMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel totalVehiculos;
    private javax.swing.JTextArea vehiculosEncontrados;
    private javax.swing.JScrollPane ventanaVehiculos;
    // End of variables declaration//GEN-END:variables
}
