/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import static RentaCar.Vehiculo.*;
import java.awt.Color;
import java.sql.SQLException;

/**
 * @author victoriapenas & josemariahernandez
 * @version 1.0
 * @since 2020-19-05
 */
public class Interfaz_RegistroVehiculos extends javax.swing.JInternalFrame {

    /**
     * Contructor Interfaz_Vehiculos
     */
    public Interfaz_RegistroVehiculos() {
        initComponents();
        ocultarCampos();
        try {
            extraerClases(jComboBox_Clase);
        } catch (SQLException ex) {
            jLabel_result.setForeground(Color.RED);
            jLabel_result.setText(ex.getSQLState() + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel_Bienvenida = new javax.swing.JLabel();
        jLabel_TipoVehículo = new javax.swing.JLabel();
        jComboBox_Selector = new javax.swing.JComboBox<>();
        jLabel_result = new javax.swing.JLabel();
        jLabel_Matricula = new javax.swing.JLabel();
        jTextField_Matricula = new javax.swing.JTextField();
        jLabel_Marca = new javax.swing.JLabel();
        jComboBox_Marca = new javax.swing.JComboBox<>();
        jLabel_Modelo = new javax.swing.JLabel();
        jTextField_Modelo = new javax.swing.JTextField();
        jLabel_precioDia = new javax.swing.JLabel();
        jTextField_precioDia = new javax.swing.JTextField();
        jLabel_Clase = new javax.swing.JLabel();
        jComboBox_Clase = new javax.swing.JComboBox<>();
        jLabel_potenciaMotor = new javax.swing.JLabel();
        jTextField_potenciaMotor = new javax.swing.JTextField();
        jLabel_numPuertasCoche = new javax.swing.JLabel();
        jTextField_numPuertasCoche = new javax.swing.JTextField();
        jLabel_Cilindrada = new javax.swing.JLabel();
        jTextField_Cilindrada = new javax.swing.JTextField();
        jCheckBox_wc = new javax.swing.JCheckBox();
        jButton_Enviar = new javax.swing.JButton();
        jButton_Limpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setClosable(true);
        setIconifiable(true);
        setTitle("REGISTRO DE VEHICULOS");
        setToolTipText("");

        jPanel.setBackground(new java.awt.Color(102, 102, 102));
        jPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_Bienvenida.setFont(new java.awt.Font("Heiti TC", 1, 22)); // NOI18N
        jLabel_Bienvenida.setForeground(new java.awt.Color(254, 255, 249));
        jLabel_Bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Bienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/administrative_tools_64px.png"))); // NOI18N
        jLabel_Bienvenida.setText("   ¡REGISTRA NUEVOS VEHÍCULOS!");

        jLabel_TipoVehículo.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_TipoVehículo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TipoVehículo.setText("Tipo de Vehículo*");

        jComboBox_Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "COCHE", "MOTO", "CARAVANA" }));
        jComboBox_Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_SelectorActionPerformed(evt);
            }
        });

        jLabel_result.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_result.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_Matricula.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_Matricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Matricula.setText("Matricula*");

        jTextField_Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MatriculaActionPerformed(evt);
            }
        });

        jLabel_Marca.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_Marca.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Marca.setText("Marca*");

        jComboBox_Marca.setFont(new java.awt.Font("Heiti TC", 1, 12)); // NOI18N
        jComboBox_Marca.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "FORD", "AUDI", "MERCEDES", "BMW" }));
        jComboBox_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MarcaActionPerformed(evt);
            }
        });

        jLabel_Modelo.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_Modelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Modelo.setText("Modelo*");

        jTextField_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ModeloActionPerformed(evt);
            }
        });

        jLabel_precioDia.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_precioDia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_precioDia.setText("Precio/Día*");

        jTextField_precioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_precioDiaActionPerformed(evt);
            }
        });

        jLabel_Clase.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_Clase.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Clase.setText("Clase*");

        jComboBox_Clase.setFont(new java.awt.Font("Heiti TC", 1, 12)); // NOI18N
        jComboBox_Clase.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_Clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBox_Clase.setOpaque(false);
        jComboBox_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ClaseActionPerformed(evt);
            }
        });

        jLabel_potenciaMotor.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_potenciaMotor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_potenciaMotor.setText("Potencia Motor*");

        jTextField_potenciaMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_potenciaMotorActionPerformed(evt);
            }
        });

        jLabel_numPuertasCoche.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_numPuertasCoche.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_numPuertasCoche.setText("Número Puertas*");

        jTextField_numPuertasCoche.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jTextField_numPuertasCoche.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_numPuertasCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numPuertasCocheActionPerformed(evt);
            }
        });

        jLabel_Cilindrada.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jLabel_Cilindrada.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Cilindrada.setText("Cilindrada*");

        jCheckBox_wc.setFont(new java.awt.Font("Heiti TC", 1, 14)); // NOI18N
        jCheckBox_wc.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_wc.setText("Dispone de WC*");
        jCheckBox_wc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_wcActionPerformed(evt);
            }
        });

        jButton_Enviar.setFont(new java.awt.Font("Heiti TC", 1, 12)); // NOI18N
        jButton_Enviar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Enviar.setText("Enviar Formulario");
        jButton_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnviarActionPerformed(evt);
            }
        });

        jButton_Limpiar.setFont(new java.awt.Font("Heiti TC", 1, 12)); // NOI18N
        jButton_Limpiar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Limpiar.setText("Limpiar");
        jButton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Bienvenida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_Modelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_numPuertasCoche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_numPuertasCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_potenciaMotor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_potenciaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jTextField_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(jLabel_Cilindrada)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_Cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                            .addComponent(jLabel_Clase)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                            .addComponent(jLabel_Marca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(jLabel_precioDia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_precioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox_wc))
                .addGap(174, 174, 174))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jButton_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_TipoVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel_Bienvenida)
                .addGap(8, 8, 8)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_TipoVehículo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Matricula)
                            .addComponent(jTextField_Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel_Marca, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Modelo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_potenciaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_potenciaMotor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_numPuertasCoche)
                            .addComponent(jTextField_numPuertasCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Clase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_precioDia)
                            .addComponent(jTextField_precioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Cilindrada)
                            .addComponent(jTextField_Cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_wc)))
                .addGap(18, 18, 18)
                .addComponent(jLabel_result, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Limpiar)
                    .addComponent(jButton_Enviar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para informar si se ha realizado correctamente el insert del
     * vehiculo
     *
     * @param resultado resultado de la operacion
     */
    public void operacioRealizada(boolean resultado) {
        if (resultado) {
            jLabel_result.setForeground(Color.GREEN);
            jLabel_result.setText("Vehiculo registrado con éxito.");
        } else {
            jLabel_result.setForeground(Color.RED);
        }
    }

    private void jComboBox_SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SelectorActionPerformed
        String selector = (String) jComboBox_Selector.getSelectedItem();
        if (selector.equals(" ")) {
            ocultarCampos();
        } else if (selector.equalsIgnoreCase("Moto")) {
            jLabel_result.setText("");
            ocultarCampos();
            jLabel_Cilindrada.setVisible(true);
            jTextField_Cilindrada.setVisible(true);
        } else if (selector.equalsIgnoreCase("Caravana")) {
            jLabel_result.setText("");
            ocultarCampos();
            jLabel_potenciaMotor.setVisible(true);
            jTextField_potenciaMotor.setVisible(true);
            jCheckBox_wc.setVisible(true);
        } else if (selector.equalsIgnoreCase("Coche")) {
            jLabel_result.setText("");
            ocultarCampos();
            jLabel_numPuertasCoche.setVisible(true);
            jTextField_numPuertasCoche.setVisible(true);
            jLabel_potenciaMotor.setVisible(true);
            jTextField_potenciaMotor.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox_SelectorActionPerformed

    private void jTextField_MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MatriculaActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_MatriculaActionPerformed

    private void jComboBox_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MarcaActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jComboBox_MarcaActionPerformed

    private void jTextField_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ModeloActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_ModeloActionPerformed

    private void jComboBox_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ClaseActionPerformed
    }//GEN-LAST:event_jComboBox_ClaseActionPerformed

    private void jButton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton_LimpiarActionPerformed

    /**
     * En función del tipo de vehiculo seleccionado, se instanciará una clase u otra.
     * Con el objetivo de realizar un insert en la tabla vehiculos
     * y en su correspondiente tabla de especificaciones.
     * @param evt evento que se ejecuta al pinchar en el JButton Enviar Formulario.
     */
    private void jButton_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnviarActionPerformed
        String tipoVehiculo = (String) jComboBox_Selector.getSelectedItem();
        switch (tipoVehiculo) {
            case "COCHE":
                try {
                    Coche coche = new Coche();
                    if (revisarCamposObligatorios() && !jTextField_potenciaMotor.getText().isEmpty()
                            && !jTextField_numPuertasCoche.getText().isEmpty()) {
                        coche.setMatricula(jTextField_Matricula.getText());
                        coche.setMarca((String) jComboBox_Marca.getSelectedItem());
                        coche.setModelo(jTextField_Modelo.getText());
                        coche.setClase(obtenerClasePK((String) jComboBox_Clase.getSelectedItem()));
                        coche.setPrecioDia(Double.parseDouble(jTextField_precioDia.getText()));
                        coche.setPotenciaMotor(Integer.parseInt(jTextField_potenciaMotor.getText()));
                        coche.setNumeroPuertas(Integer.parseInt(jTextField_numPuertasCoche.getText()));
                        coche.registrarVehiculo();
                        operacioRealizada(true);
                    } else {
                        operacioRealizada(false);
                        throw new RCException("Hay datos del coche sin rellenar.");
                    }
                } catch (Exception ex) {
                    operacioRealizada(false);
                    jLabel_result.setText(ex.getMessage());
                    ex.printStackTrace();
                }
                break;
            case "MOTO":
                try {
                    Moto moto = new Moto();
                    if (revisarCamposObligatorios() && !jTextField_Cilindrada.getText().isEmpty()) {
                        moto.setMatricula(jTextField_Matricula.getText());
                        moto.setMarca((String) jComboBox_Marca.getSelectedItem());
                        moto.setModelo(jTextField_Modelo.getText());
                        moto.setClase(obtenerClasePK((String) jComboBox_Clase.getSelectedItem()));
                        moto.setPrecioDia(Double.parseDouble(jTextField_precioDia.getText()));
                        moto.setCilindrada(Integer.parseInt(jTextField_Cilindrada.getText()));
                        moto.registrarVehiculo();
                        operacioRealizada(true);
                    } else {
                        operacioRealizada(false);
                        throw new RCException("Hay datos de la moto sin rellenar.");
                    }
                } catch (Exception ex) {
                    operacioRealizada(false);
                    jLabel_result.setText(ex.getMessage());
                }
                break;
            case "CARAVANA":
                try {
                    Caravana caravana = new Caravana();
                    if (revisarCamposObligatorios() && !jTextField_potenciaMotor.getText().isEmpty()) {
                        caravana.setMatricula(jTextField_Matricula.getText());
                        caravana.setMarca((String) jComboBox_Marca.getSelectedItem());
                        caravana.setModelo(jTextField_Modelo.getText());
                        caravana.setClase(obtenerClasePK((String) jComboBox_Clase.getSelectedItem()));
                        caravana.setPrecioDia(Double.parseDouble(jTextField_precioDia.getText()));
                        caravana.setPotenciaMotor(Integer.parseInt(jTextField_potenciaMotor.getText()));
                        caravana.setWc(estaDisponible(jCheckBox_wc));
                        caravana.registrarVehiculo();
                        operacioRealizada(true);
                    } else {
                        operacioRealizada(false);
                        throw new RCException("Hay datos de la caravana sin rellenar.");
                    }
                } catch (NumberFormatException ex) {
                    operacioRealizada(false);
                    jLabel_result.setText("Por favor, verifica que todos los campos tengan un formato válido.");
                } catch (Exception ex) {
                    operacioRealizada(false);
                    jLabel_result.setText(ex.getMessage());
                }
                break;
            default:
                jLabel_result.setForeground(Color.RED);
                jLabel_result.setText("Por favor, selecciona el tipo de vehiculo que quieres registrar");
                break;
        }
    }//GEN-LAST:event_jButton_EnviarActionPerformed
    private void jTextField_potenciaMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_potenciaMotorActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_potenciaMotorActionPerformed

    private void jTextField_numPuertasCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numPuertasCocheActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_numPuertasCocheActionPerformed

    private void jCheckBox_wcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_wcActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jCheckBox_wcActionPerformed

    private void jTextField_precioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_precioDiaActionPerformed
        // NO ACTION
    }//GEN-LAST:event_jTextField_precioDiaActionPerformed

    /**
     * Método para comprobar si hay datos vacíos que son obligatorios para el
     * registro del vehiculo
     *
     * @return devuelve true/false en función del chequeo
     */
    private boolean revisarCamposObligatorios() {
        boolean todosRellenados = true;
        if (jTextField_Matricula.getText().isEmpty() || jTextField_Matricula.getText().isEmpty()
                || jComboBox_Marca.getSelectedItem().equals("") || jTextField_Modelo.getText().isEmpty()
                || jComboBox_Clase.getSelectedItem().equals("") || jTextField_precioDia.getText().isEmpty()) {
            todosRellenados = false;
        } else {
            todosRellenados = true;
        }

        return todosRellenados;
    }

    /**
     * Limpia los datos de la ventana Interfaz_Vehículos
     */
    public void limpiarCampos() {
        ocultarCampos();
        // Borrando textos
        jTextField_Cilindrada.setText("");
        jTextField_Matricula.setText("");
        jTextField_Modelo.setText("");
        jTextField_precioDia.setText("");
        jTextField_potenciaMotor.setText("");
        jTextField_precioDia.setText("");
        jTextField_numPuertasCoche.setText("");
        jComboBox_Selector.setSelectedItem(" ");
        jComboBox_Marca.setSelectedItem(" ");
        jComboBox_Clase.setSelectedItem(" ");
        // Seteando a uncheck los checkbox
        jCheckBox_wc.setSelected(false);

    }

    /**
     * Método para ocultar paneles según la seleccion del tipo de vehiculo
     */
    public void ocultarCampos() {
        jLabel_Cilindrada.setVisible(false);
        jTextField_Cilindrada.setVisible(false);
        jLabel_potenciaMotor.setVisible(false);
        jTextField_potenciaMotor.setVisible(false);
        jCheckBox_wc.setVisible(false);
        jLabel_numPuertasCoche.setVisible(false);
        jTextField_numPuertasCoche.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Enviar;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JCheckBox jCheckBox_wc;
    private javax.swing.JComboBox<String> jComboBox_Clase;
    private javax.swing.JComboBox<String> jComboBox_Marca;
    private javax.swing.JComboBox<String> jComboBox_Selector;
    private javax.swing.JLabel jLabel_Bienvenida;
    private javax.swing.JLabel jLabel_Cilindrada;
    private javax.swing.JLabel jLabel_Clase;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_Matricula;
    private javax.swing.JLabel jLabel_Modelo;
    private javax.swing.JLabel jLabel_TipoVehículo;
    private javax.swing.JLabel jLabel_numPuertasCoche;
    private javax.swing.JLabel jLabel_potenciaMotor;
    private javax.swing.JLabel jLabel_precioDia;
    private javax.swing.JLabel jLabel_result;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTextField_Cilindrada;
    private javax.swing.JTextField jTextField_Matricula;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_numPuertasCoche;
    private javax.swing.JTextField jTextField_potenciaMotor;
    private javax.swing.JTextField jTextField_precioDia;
    // End of variables declaration//GEN-END:variables
}
