/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package RentaCar;

import javax.swing.JOptionPane;

/**
 * @author victoriapenas & josemariahernandez
 * @version 1.0
 * @since 2020-18-05
 */
public class Interfaz_Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_Clientes
     */
    ComboBox cbx = new ComboBox();
    /**
     * 
     */
    public Interfaz_Clientes() {
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_clienteNIF = new javax.swing.JLabel();
        jTextField_clienteNIF = new javax.swing.JTextField();
        jLabel2_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel4_apellido1 = new javax.swing.JLabel();
        jLabel3_telefono = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jLabel6_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jTextField_apellido1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField_apellido2 = new javax.swing.JTextField();
        jLabel10_apellido2 = new javax.swing.JLabel();
        jLabel7_password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 153, 204));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel_clienteNIF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_clienteNIF.setText("Doc. NIF");

        jLabel2_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2_nombre.setText("Nombre");

        jLabel4_apellido1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4_apellido1.setText("Primer Apellido");

        jLabel3_telefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3_telefono.setText("Teléfono");

        jTextField_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonoActionPerformed(evt);
            }
        });

        jLabel6_email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6_email.setText("E-mail");

        jButton1.setText("Enviar Formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField_apellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_apellido2ActionPerformed(evt);
            }
        });

        jLabel10_apellido2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10_apellido2.setText("Segundo Apellido");

        jLabel7_password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7_password.setText("Introduzca una Contraseña");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_clienteNIF)
                            .addComponent(jLabel2_nombre)
                            .addComponent(jLabel3_telefono))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(jTextField_telefono)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_clienteNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4_apellido1)
                        .addGap(29, 29, 29)
                        .addComponent(jTextField_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6_email)
                            .addGap(34, 34, 34)
                            .addComponent(jTextField_email))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10_apellido2)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_clienteNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_clienteNIF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3_telefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4_apellido1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10_apellido2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6_email))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7_password)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   // Método para limpiar los jTextField

    public void limpiar() {
        jTextField_clienteNIF.setText("");
        jTextField_nombre.setText("");
        jTextField_apellido1.setText("");
        jTextField_apellido2.setText("");
        jTextField_telefono.setText("");
        jTextField_email.setText("");

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Recojo datos del botón de enviar formulario
        String nif, nom, ape1, ape2, tel, mail, pass, codUser;

        // Datos recogidos del formulario
        nif = jTextField_clienteNIF.getText();
        nom = jTextField_nombre.getText();
        ape1 = jTextField_apellido1.getText();
        ape2 = jTextField_apellido2.getText();
        tel = jTextField_telefono.getText();
        mail = jTextField_email.getText();

        // Stringify un char extraído del passwordfield
        String passText = new String(jPasswordField1.getPassword());
        pass = passText;

        // TODO --> Datos fijados manualmente
        int rol = 1;
        codUser = "123"; // TODO: añadir en un textfield

        // Control de clientes y mensajes informativos
        Control_Clientes control = new Control_Clientes(nif, nom, ape1, ape2, tel, mail, rol, pass, codUser);
        if (!nif.equals("") && !nom.equals("") && !ape1.equals("") && !ape2.equals("") && !tel.equals("") && !mail.equals("")
                && !pass.equals("")) {
            if (control.registrarDatosCliente("clientes") && control.registrarDatosUsuario("usuarios")) {
                JOptionPane.showMessageDialog(null, "Cliente registrado con éxito.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                limpiar();

            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el cliente");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hay campos obligatorios");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_apellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_apellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apellido2ActionPerformed

    private void jTextField_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonoActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10_apellido2;
    private javax.swing.JLabel jLabel2_nombre;
    private javax.swing.JLabel jLabel3_telefono;
    private javax.swing.JLabel jLabel4_apellido1;
    private javax.swing.JLabel jLabel6_email;
    private javax.swing.JLabel jLabel7_password;
    private javax.swing.JLabel jLabel_clienteNIF;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_apellido1;
    private javax.swing.JTextField jTextField_apellido2;
    private javax.swing.JTextField jTextField_clienteNIF;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
